# Generated by Django 5.0.3 on 2024-03-27 03:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
